owner: soumydip
repo: ucoder_insights_status_page

sites:
  - name: Ucoder Insight
    url: https://insights.ucoder.in

status-website:
  # Custom domain
  cname: status.insights.ucoder.in
  logoUrl: https://insights.ucoder.in/icon.png
  name: Ucoder Insight Status
  introTitle: "**Ucoder Insight** — Real-time system status"
  introMessage: "Here you can view the real-time uptime and incident history of **Ucoder Insight**. Any issues or outages will be updated here immediately."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
